task_manager/labels/urls.py
from django.urls import path

from task_manager.labels import views

urlpatterns = [
    path('',
         views.LabelsListView.as_view(), name='labels'),
    path('create/',
         views.LabelsCreateView.as_view(), name='label_create'),
    path('<int:pk>/update/',
         views.LabelsUpdateView.as_view(), name='label_update'),
    path('<int:pk>/delete/',
         views.LabelsDeleteView.as_view(), name='label_delete'),
]

task_manager/tasks/urls.py
from django.urls import path

from task_manager.tasks import views

urlpatterns = [
    path('',
         views.TasksListView.as_view(), name='tasks'),
    path('create/',
         views.TasksCreateView.as_view(), name='tasks_create'),
    path('<int:pk>/update/',
         views.TasksUpdateView.as_view(), name='tasks_update'),
    path('<int:pk>/delete/',
         views.TasksDeleteView.as_view(), name='tasks_delete'),
    path('<int:pk>/',
         views.TaskDetailView.as_view(), name='task_card'),
]

task_manager/urls.py
from django.conf.urls.i18n import set_language
from django.contrib import admin
from django.urls import include, path

from task_manager import views
from task_manager.users.views import UserLoginView, UserLogoutView

urlpatterns = [
    path('set-language/', set_language, name='set_language'),
    path('', views.index, name='home'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path("i18n/", include("django.conf.urls.i18n")),
]

task_manager/users/urls.py
from django.urls import path

from task_manager.users import views

urlpatterns = [
    path('',
         views.UserListView.as_view(), name='users'),
    path('create/',
         views.UserCreateView.as_view(), name='user-create'),
    path('<int:pk>/update/',
         views.UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/',
         views.UserDeleteView.as_view(), name='delete_user'),
]

task_manager/labels/models.py
from django.db import models


class Label(models.Model):
    name = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/statuses/models.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.db import models

from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.users.models import CustomUser


class Task(models.Model):
    name = models.CharField(max_length=150, unique=True)
    description = models.TextField()
    status = models.ForeignKey(Status, on_delete=models.CASCADE)
    performer = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL, null=True, blank=True)
    creator = models.ForeignKey(CustomUser,
                                on_delete=models.CASCADE,
                                related_name='created_tasks')
    labels = models.ManyToManyField(Label, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy

from .models import CustomUser


class UserRegistrationForm(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['username',
                  'first_name',
                  'last_name',
                  'password1',
                  'password2']


class UserUpdateForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput(), required=False)
    password2 = forms.CharField(widget=forms.PasswordInput(), required=False)

    class Meta:
        model = CustomUser
        fields = ['username',
                  'first_name',
                  'last_name',
                  'password1',
                  'password2']

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get('password1')
        password2 = cleaned_data.get('password2')

        if password1 and password1 != password2:
            raise ValidationError("Passwords do not match.")

        return cleaned_data


class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(
        max_length=150,
        widget=forms.TextInput(
            attrs={'class': 'form-control',
                   'placeholder': gettext_lazy('Username'), 'label': "1"}),
        label=gettext_lazy('Username')
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control',
                   'placeholder': gettext_lazy('Password')}),
        label=gettext_lazy('Password')
    )

task_manager/labels/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Label

logger = logging.getLogger(__name__)


class LabelsListView(LoginRequiredMixin, ListView):
    model = Label
    template_name = 'labels.html'
    context_object_name = 'labels'
    login_url = "/login"

    def handle_no_permission(self):
        messages.error(self.request, gettext_lazy(
            'You need to be logged in to perform this action.'))
        return super().handle_no_permission()


class LabelsCreateView(LoginRequiredMixin, CreateView):
    model = Label
    template_name = 'label_create.html'
    fields = ['name']
    context_object_name = 'labels'
    success_url = reverse_lazy('labels')
    login_url = "/login"

    def handle_no_permission(self):
        messages.error(self.request, gettext_lazy(
            'You need to be logged in to perform this action.'))
        return super().handle_no_permission()

    def form_valid(self, form):
        name = form.cleaned_data['name']
        if Label.objects.filter(name=name).exists():
            messages.error(self.request, gettext_lazy(
                'Label with this name already exists.'))
            return redirect('label_create')
        messages.success(self.request, gettext_lazy(
            'Label successfully create'))
        return super().form_valid(form)


class LabelsUpdateView(LoginRequiredMixin, UpdateView):
    model = Label
    template_name = 'label_update.html'
    fields = ['name']
    success_url = reverse_lazy('labels')
    context_object_name = "label"
    login_url = "/login"

    def handle_no_permission(self):
        messages.error(self.request, gettext_lazy(
            'You need to be logged in to perform this action.'))
        return super().handle_no_permission()

    def dispatch(self, request, *args, **kwargs):
        label = self.get_object()
        if request.method == "POST":
            if label.task_set.exists():
                messages.error(request, gettext_lazy(
                    'Cannot update label because it is associated with tasks.'))
                return redirect('labels')
            messages.success(request, gettext_lazy('Label successfully update'))
        return super().dispatch(request, *args, **kwargs)


class LabelsDeleteView(LoginRequiredMixin, DeleteView):
    model = Label
    template_name = 'label_delete.html'
    success_url = reverse_lazy('labels')
    login_url = "/login"

    def handle_no_permission(self):
        messages.error(self.request, gettext_lazy(
            'You need to be logged in to perform this action.'))
        return super().handle_no_permission()

    def dispatch(self, request, *args, **kwargs):
        label = self.get_object()
        if request.method == "POST":
            if label.task_set.exists():
                messages.error(request, gettext_lazy(
                    'Cannot delete label because it is associated with tasks.'))
                return redirect('labels')
            messages.success(request, gettext_lazy('Label successfully delete'))
        return super().dispatch(request, *args, **kwargs)

task_manager/statuses/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from .models import Status

logger = logging.getLogger(__name__)


class StatusesListView(LoginRequiredMixin, ListView):
    model = Status
    template_name = 'statuses.html'
    context_object_name = 'statuses'
    login_url = "/login"

    def handle_no_permission(self):
        messages.error(self.request, gettext_lazy(
            'You need to be logged in to perform this action.'))
        return super().handle_no_permission()


class StatusesCreateView(LoginRequiredMixin, CreateView):
    model = Status
    template_name = 'status_create.html'
    fields = ['name']
    context_object_name = 'statuses'
    success_url = reverse_lazy('statuses')
    login_url = "/login"

    def handle_no_permission(self):
        messages.error(self.request, gettext_lazy(
            'You need to be logged in to perform this action.'))
        return super().handle_no_permission()

    def dispatch(self, request, *args, **kwargs):
        if request.method == "POST":
            messages.success(request,
                             gettext_lazy('Status successfully create'))
        return super().dispatch(request, *args, **kwargs)


class StatusesUpdateView(LoginRequiredMixin, UpdateView):
    model = Status
    template_name = 'status_update.html'
    fields = ['name']
    success_url = reverse_lazy('statuses')
    context_object_name = "status"
    login_url = "/login"

    def handle_no_permission(self):
        messages.error(self.request, gettext_lazy(
            'You need to be logged in to perform this action.'))
        return super().handle_no_permission()

    def dispatch(self, request, *args, **kwargs):
        if request.method == "POST":
            messages.success(request,
                             gettext_lazy('Status successfully update'))
        return super().dispatch(request, *args, **kwargs)


class StatusesDeleteView(LoginRequiredMixin, DeleteView):
    model = Status
    template_name = 'status_delete.html'
    success_url = reverse_lazy('statuses')
    login_url = "/login"

    def handle_no_permission(self):
        messages.error(self.request, gettext_lazy(
            'You need to be logged in to perform this action.'))
        return super().handle_no_permission()

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if request.method == "POST":
            if self.object.task_set.exists():
                messages.error(request, gettext_lazy('Cannot delete status'))
                return redirect('statuses')
            messages.success(request,
                             gettext_lazy('Status successfully deleted'))
        return super().dispatch(request, *args, **kwargs)

task_manager/tasks/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView

from task_manager.tasks.filters import TaskFilter

from .models import CustomUser, Label, Status, Task

logger = logging.getLogger(__name__)


class TasksListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'tasks.html'
    context_object_name = 'tasks'
    filterset_class = TaskFilter
    login_url = "/login"

    def handle_no_permission(self):
        messages.error(self.request, gettext_lazy(
            'You need to be logged in to perform this action.'))
        return super().handle_no_permission()

    def get_queryset(self):
        queryset = super().get_queryset()

        status = self.request.GET.get('status')
        performer = self.request.GET.get('performer')
        label = self.request.GET.get('labels')
        my_tasks = self.request.GET.get('my_tasks')

        if status:
            queryset = queryset.filter(status__name=status)
        if performer:
            queryset = queryset.filter(performer__id=performer)
        if label:
            queryset = queryset.filter(labels__id=label)
        if my_tasks == "on":
            queryset = queryset.filter(creator=self.request.user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['statuses'] = (
            Task.objects.values_list('status__name', flat=True).distinct())
        context['performers'] = CustomUser.objects.all().distinct()
        context['labels'] = Label.objects.all()
        context['current_filters'] = {
            'status': self.request.GET.get('status', ''),
            'performer': self.request.GET.get('performer', ''),
            'labels': self.request.GET.get('labels', ''),
            'my_tasks': self.request.GET.get('my_tasks', ''),
        }
        return context


class TasksCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = 'tasks_create.html'
    fields = ['name', 'description', 'status', 'performer', 'labels']
    context_object_name = 'tasks'
    success_url = reverse_lazy('tasks')
    login_url = "/login"

    def handle_no_permission(self):
        messages.error(self.request, gettext_lazy(
            'You need to be logged in to perform this action.'))
        return super().handle_no_permission()

    def dispatch(self, request, *args, **kwargs):
        if request.method == "POST":
            messages.success(request, gettext_lazy('Task successfully create'))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['statuses'] = Status.objects.all()
        context['labels'] = Label.objects.all()
        context['performers'] = CustomUser.objects.all()
        return context

    def form_valid(self, form):
        form.instance.creator = self.request.user
        print(self.request.POST.getlist('labels'))
        return super().form_valid(form)


class TasksUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = 'tasks_update.html'
    fields = ['name', 'description', 'status', 'performer', 'labels']
    context_object_name = 'task'
    success_url = reverse_lazy('tasks')
    login_url = "/login"

    def handle_no_permission(self):
        messages.error(self.request, gettext_lazy(
            'You need to be logged in to perform this action.'))
        return super().handle_no_permission()

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.creator != request.user:
            messages.error(request, gettext_lazy('You do not '
                            'have permission to update this task.'))
            return redirect(self.success_url)
        if request.method == "POST":
            messages.success(request, gettext_lazy('Task successfully update'))
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        task = self.get_object()
        context['statuses'] = Status.objects.all()
        context['labels'] = Label.objects.all()
        context['task_labels'] = (
            list(task.labels.values_list('id', flat='True')))
        context['performers'] = CustomUser.objects.all()
        return context


class TasksDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'tasks_delete.html'
    success_url = reverse_lazy('tasks')
    login_url = "/login"

    def handle_no_permission(self):
        messages.error(self.request, gettext_lazy(
            'You need to be logged in to perform this action.'))
        return super().handle_no_permission()

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.creator != request.user:
            messages.error(request, gettext_lazy("You do not "
                        "have permission to delete this task."))
            return redirect(self.success_url)
        if request.method == "POST":
            messages.success(request, gettext_lazy('Task successfully delete'))
        return super().dispatch(request, *args, **kwargs)


class TaskDetailView(DetailView):
    model = Task
    template_name = 'task_card.html'
    context_object_name = 'task'

task_manager/views.py
import logging

from django.shortcuts import render

logger = logging.getLogger(__name__)


def index(request):
    return render(request, 'index.html')

task_manager/templates/flash.html
{% if messages %}
    <div class="alert-container">
        {% for message in messages %}
            {% if message.tags == 'error' %}
                <div class="alert alert-danger">{{ message }}</div>
            {% else %}
                <div class="alert alert-{{message.tags}}">{{ message }}</div>
            {% endif %}
        {% endfor %}
    </div>
{% endif %}

task_manager/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
<head>
    {% load static %}
    {% load django_bootstrap5 %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Navbar Static</title>
    {% bootstrap_css %}
</head>
<body>
    <!-- Подключаем шапку (navbar) -->
    {% include 'navbar.html' %}

    <!-- Основной контент -->
    {% include 'flash.html' %}
    <div class="container mt-4">
        {% block content %}
        <h1>{% trans "Greetings from Danlo" %}</h1>
        {% endblock %}
    </div>

    {% bootstrap_javascript %}
</body>
</html>

task_manager/templates/label_create.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
<head>
    {% load static %}
    {% load django_bootstrap5 %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Navbar Static</title>
    {% bootstrap_css %}
</head>
<body>
    <!-- Подключаем шапку (navbar) -->
    {% include 'navbar.html' %}

    <!-- Основной контент -->
    {% include 'flash.html' %}
    <div class="container mt-4">
        <h1 class="my-4">{% trans 'Create label' %}</h1>
      <form action="{% url 'label_create' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
          <label class="form-label" for="id_name">{% trans 'Name' %}</label>
          <input type="text" name="name" maxlength="100" class="form-control" placeholder="{% trans 'Name' %}" required="" id="id_name">
        </div>
        <input class="btn btn-primary" type="submit" value="{% trans 'Create' %}">
      </form>
    </div>

task_manager/templates/label_delete.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
<head>
    {% load static %}
    {% load django_bootstrap5 %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Navbar Static</title>
    {% bootstrap_css %}
</head>
<body>
    <!-- Подключаем шапку (navbar) -->
    {% include 'navbar.html' %}

    <!-- Основной контент -->
    <div class="container wrapper flex-grow-1">
        <h1>{% trans "Delete label" %}</h1>
        <p>{% trans "Are you sure you want to delete " %} {{ label.name }}?</p>
    <form method="POST">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="{% trans 'Yes, delete' %}">
    </form>
    <a href="{% url 'labels' %}">{% trans 'Cancel' %}</a>
    </div>

    {% bootstrap_javascript %}
</body>
</html>

task_manager/templates/navbar.html
{% load i18n %}
<nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">{% trans "Tasks manager" %}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users' %}">{% trans "Users" %}</a>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'user-create' %}">{% trans "Sign up" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">{% trans "log in" %}</a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'statuses' %}">{% trans "Statuses" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'labels' %}">{% trans "Labels" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tasks' %}">{% trans "Tasks" %}</a>
                    </li>
                    <li class="nav-item">
                        <form action="{% url 'logout' %}" method="post" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" class="nav-link" style="border: none; background: none; padding: 2;">
                                {% trans "log out" %}
                            </button>
                        </form>
                    </li>
                {% endif %}
            </ul>

            <div class="ms-auto">
            {% get_current_language as CURRENT_LANGUAGE %}
                {% if CURRENT_LANGUAGE == "ru" %}
                    <form method="post" action="{% url 'set_language' %}">
                        {% csrf_token %}
                        <input type="hidden" name="language" value="en" />
                        <button type="submit">English</button>
                    </form>
                {% elif CURRENT_LANGUAGE == "en" %}
                <form method="post" action="{% url 'set_language' %}">
                    {% csrf_token %}
                    <input type="hidden" name="language" value="ru" />
                    <button type="submit">Русский</button>
                </form>
                {% endif %}
            </div>

        </div>
    </div>
</nav>

task_manager/templates/status_create.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
<head>
    {% load static %}
    {% load django_bootstrap5 %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Navbar Static</title>
    {% bootstrap_css %}
</head>
<body>
    <!-- Подключаем шапку (navbar) -->
    {% include 'navbar.html' %}

    <!-- Основной контент -->
    <div class="container mt-4">
        <h1 class="my-4">{% trans 'Create status' %}</h1>
      <form action="{% url 'status_create' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
          <label class="form-label" for="id_name">{% trans 'Name' %}</label>
          <input type="text" name="name" maxlength="100" class="form-control" placeholder="{% trans 'Name' %}" required="" id="id_name">
        </div>
        <input class="btn btn-primary" type="submit" value="{% trans 'Create' %}">
      </form>
    </div>

task_manager/templates/status_update.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
<head>
    {% load static %}
    {% load django_bootstrap5 %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Navbar Static</title>
    {% bootstrap_css %}
</head>
<body>
    <!-- Подключаем шапку (navbar) -->
    {% include 'navbar.html' %}

    <!-- Основной контент -->
    <div class="container mt-4">
        <h1 class="my-4">{% trans 'Create status' %}</h1>
      <form action="{% url 'status_update' pk=status.id %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
          <label class="form-label" for="id_name">{% trans 'Name' %}</label>
          <input type="text" name="name" maxlength="100" class="form-control" value="{{ status.name }}" placeholder="{% trans 'Name' %}" required="" id="id_name">
        </div>
        <input class="btn btn-primary" type="submit" value="{% trans 'Update' %}">
      </form>
    </div>

task_manager/templates/tasks_create.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
<head>
    {% load static %}
    {% load django_bootstrap5 %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Navbar Static</title>
    {% bootstrap_css %}
</head>
<body>
    {% include 'navbar.html' %}
    {% include 'flash.html' %}

    <!-- Основной контент -->
    <div class="container mt-4">
        <h1 class="my-4">{% trans 'Create tasks' %}</h1>
      <form action="{% url 'tasks_create' %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
          <label class="form-label" for="id_name">{% trans 'Name' %}</label>
          <input type="text" name="name" maxlength="100" class="form-control" placeholder="{% trans 'Name' %}" required="" id="id_name">
        </div>
        <div class="mb-3">
          <label class="form-label" for="description">{% trans 'Description' %}</label>
          <textarea name="description" cols="40" rows="10" maxlength="500" class="form-control" placeholder="{% trans 'description' %}" required="" id="description"></textarea>
        </div>
        <div class="mb-3">
          <label class="form-label" for="status">{% trans 'Status' %}</label>
          <select name="status" class="form-control" required id="status">
              <option value="" selected disabled>-----------</option>
              {% for status in statuses %}
              <option value="{{ status.id }}">{{status.name}}</option>
              {% endfor %}
          </select>
        </div>
        <div class="mb-3">
          <label class="form-label" for="performer">{% trans 'Performer' %}</label>
          <select name="performer" class="form-control" id="performer">
              <option value="" selected>-----------</option>
              {% for performer in performers %}
              <option value="{{ performer.id }}">{{performer.first_name}} {{performer.last_name}}</option>
              {% endfor %}
          </select>
        </div>
        <label class="form-label" for="labels">{% trans 'Labels' %}</label>
          <select name="labels" class="form-control" id="labels" multiple>
              {% for label in labels %}
              <option value="{{ label.id }}">{{label.name}}</option>
              {% endfor %}
          </select>
        <input class="btn btn-primary" type="submit" value="{% trans 'Create' %}">
      </form>
    </div>

task_manager/templates/tasks_update.html
<!DOCTYPE html>
<html lang="en">
{% load i18n %}
<head>
    {% load static %}
    {% load django_bootstrap5 %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Navbar Static</title>
    {% bootstrap_css %}
</head>
<body>
    {% include 'navbar.html' %}
    {% include 'flash.html' %}
    <!-- Основной контент -->
    <div class="container mt-4">
        <h1 class="my-4">{% trans 'Update tasks' %}</h1>
      <form action="{% url 'tasks_update' pk=task.id  %}" method="POST">
        {% csrf_token %}
        <div class="mb-3">
          <label class="form-label" for="id_name">{% trans 'Name' %}</label>
          <input type="text" name="name" maxlength="100" class="form-control" placeholder="{% trans 'Name' %}" required="" id="id_name" value="{{task.name}}">
        </div>
        <div class="mb-3">
          <label class="form-label" for="id_description">{% trans 'Description' %}</label>
          <textarea name="description" cols="40" rows="10" maxlength="500" class="form-control" placeholder="{% trans 'description' %}" required="" id="id_description">{{task.description}}</textarea>
        </div>
        <div class="mb-3">
          <label class="form-label" for="id_status">{% trans 'Status' %}</label>
          <select name="status" class="form-control" required="" id="id_status">
              <option>-----------</option>
              {% for status in statuses %}
              <option value="{{ status.id }}"{%if status.id == task.status.id%}selected{% endif %}>{{status.name}}</option>
              {% endfor %}
          </select>
        </div>
        <div class="mb-3">
          <label class="form-label" for="id_executor">{% trans 'Performer' %}</label>
          <select name="performer" class="form-control" required="" id="id_executor">
              <option>-----------</option>
              {% for performer in performers %}
              <option value="{{ performer.id }}"{%if performer.id == task.performer.id%}selected{% endif %}>{{performer.first_name}} {{performer.last_name}}</option>
              {% endfor %}
          </select>
        </div>
        <label class="form-label" for="id_labels">{% trans 'Labels' %}</label>
          <select name="labels" class="form-control" required="" id="id_labels" multiple>
              {% for label in labels %}
              <option value="{{ label.id }}"{%if label.id in task_labels%}selected{% endif %}>{{label.name}}</option>
              {% endfor %}
          </select>
        <input class="btn btn-primary" type="submit" value="{% trans 'Change' %}">
      </form>
    </div>